### ISSUE TITLE
Some Tray Icons are not working

### ISSUE THREAD

**Issue by mikehlim** [i3-gnome/i3-gnome#39]
I'm using diodon, pa-applet, caffeine, redshift-gtk, nm-applet, blueman-applet as tray icons, but I only see the pa-applet. Is it because Gnome session take over the tray icons? how to make it visible all tray icons? or is it a bug? Any insight would be greatly appreciated.

**Comment by jcstr** [comment]
GNOME 3.34 has just arrived, if you updated, it might be buggy at the beggining, let's just give time to get an stable environment. This update focus on `gnome-session`, when this updates it usually breaks or something stop working.

**Comment by mikehlim** [comment]
@jcstr Thank you for checking in. I'm actually running Ubuntu 18.04 with GNOME Shell 3.28.4.

**Comment by jcstr** [comment]
@mikehlim No problem, in your case you ~~should~~ must update to GNOME 3.32 at least to get it work, that's because i3-gnome basically grabs the components of GNOME and every update it changes, and that changes regard gnome-session. I invite you to read the [wiki](https://github.com/i3-gnome/i3-gnome/wiki) and all the issues (open/closed) to get more info about.

**Comment by mikehlim** [comment]
Thank you. I will give a shot and update.

**Comment by mikehlim** [comment]
It worked on GNOME 3.30 (kali linux 2019.3). Thank you.
