### ISSUE TITLE
Gnome 3.34 makes i3-gnome unusable

### ISSUE THREAD

**Issue by innerout** [i3-gnome/i3-gnome#40]
After upgrading to Gnome 3.34 , i cannot use i3-Gnome anymore. 
I can login to i3 without Gnome.
After logging in i3+Gnome session with my user the image below appears.
![Screenshot](https://user-images.githubusercontent.com/11080614/65327752-6f0dfb80-dbbd-11e9-99e8-2b2b369868c3.png)

**Comment by deanproxy** [comment]
Same issue with me.

**Comment by bayi** [comment]
Reinstalling the package ( doing `git pull && sudo make install `) solved that issue for me, i3-gnome starts now but only if i start it from a terminal ( after starting `sudo Xorg`  then `DISPLAY=:0 gnome-session --session i3-gnome` ) but it fails to launch from gdm, i3 complaints that there is "another window manager running" and simply dies after im dropped in to a gnome classic desktop.

Don't know how to go further from here

**Comment by muktupavels** [comment]
You need to add/use `--builtin` with `gnome-session`, otherwise by default it will try to start session using systemd. Or make changes needed to support starting with systemd.

https://github.com/i3-gnome/i3-gnome/blob/master/session/gnome-session-i3
> env GNOME_SHELL_SESSION_MODE=classic gnome-session --session i3-gnome "$@"

Update to:
`gnome-session --builtin --session i3-gnome "$@"`

**Comment by innerout** [comment]
I can confirm @muktupavels solution works.
