### ISSUE TITLE
no wallpaper

### ISSUE THREAD

**Issue by toketin** [i3-gnome/i3-gnome#44]
Hi, I've discovered this project today since I'm an i3 user, but I can't get the wallpaper working on it. I've tried to set it both from gnome-control-center than gnome-tweaks. On i3wm standalone I was using `wal -R` to set the wallpaper, but now it doesn't work anymore under i3-gnome session.

Thanks!
Marco

**Comment by jcstr** [comment]
I invite you to use [feh](https://wiki.archlinux.org/index.php/Feh) to manage the wallpaper in a simple way, once you install it you can add it to your i3 config file:

```
# misc
exec_always --no-startup-id feh --randomize --bg-fill ~/Pictures/walls
```

**Comment by toketin** [comment]
Thanks jcstr with `feh` the wallpaper is set correctly. But another user told me that he can set it under `gnome-control-center` or `gnome-tweaks` successfully.

**Comment by jcstr** [comment]
Looks like the other user did some modifications to `i3-gnome` because I've tried to change the wallpaper whit the tools you mention but it doesn't work for me.

I want to clarify that (almost) everyone that uses `i3-gnome` make some modifications to get it work by their own way and also that in some cases they're using it in older versions of GNOME.

So I suggest you to research for this case and share your approach here, if you wish.

**Comment by fnkr** [comment]
FYI: I use this command to load the wallpaper from GNOME with `feh`.

```sh
exec --no-startup-id gio cat "$(gsettings get org.gnome.desktop.background picture-uri | sed -E "s/^'(.*)'$/\1/")" | feh --bg-scale -
```

**Comment by jcstr** [comment]
@fnkr that's a cool trick, thanks!

**Comment by jcstr** [comment]
closed due lack of activity.
