### ISSUE TITLE
Not working on fedora 30

### ISSUE THREAD

**Issue by roker** [i3-gnome/i3-gnome#47]
After selecting i3 + Gnome and logging in, you are just logged out. If you need some logs/tests just ask.

**Comment by jcstr** [comment]
I think it would be useful if you show us the version of GNOME that causes the issue. We focus on the latest version, so, if you're on an old version of GNOME the approach to fix this it should update to the latest version.

**Comment by roker** [comment]
<?xml version="1.0"?>
<gnome-version>
 <platform>3</platform>
 <minor>32</minor>
 <micro>2</micro>
 <distributor>GNOME.Org</distributor>
 <date>2019-05-07</date>
</gnome-version>

**Comment by jcstr** [comment]
Well, looks like you're using 3.32.2, recently the script that grabs all the required components, just check [here](https://github.com/i3-gnome/i3-gnome/blob/master/session/i3-gnome.session).

The main thing here is that some components have changed between 3.32.2 and 3.34

That's why you must update in order to integrate i3 onto GNOME.

**Comment by jcstr** [comment]
closed due lack of activity.
