### ISSUE TITLE
Missing icons from tray with Gnome-Flashback 

### ISSUE THREAD

**Issue by innerout** [i3-gnome/i3-gnome#59]
When I have enabled in my i3 config tray_output or  gnome-flashback the tray icons from the status bar disappear. Does a workaround exist to bypass this issue?

**Comment by innerout** [comment]
Do you have any idea why gnome-flashback could hide tray icons? @muktupavels

**Comment by muktupavels** [comment]
Hmm, try disabling status notifier watcher - `gsettings set org.gnome.gnome-flashback status-notifier-watcher false`.

If missing tray icons are built with `libappindicator` then it should help. If I remember correctly then libappindicator fallbacks to GtkStatusIcon if there is not status notifier watcher. As gnome-flashback provides that D-Bus service/interface it does not do that. That is actually problem/bug in `libappindicator` because it does not check if there is any host that will show indicator / status notifier item.

**Comment by innerout** [comment]
Thanks that was the solution!
